package com.group3.basic.netcracker.backend.controller;
import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;
import com.group3.basic.netcracker.backend.entity.Attendance;
import com.group3.basic.netcracker.backend.report.ExcelAttendanceReport;
import com.group3.basic.netcracker.backend.service.AttendanceService;
 
/**
 * A Spring controller that allows the users to download an Excel document
 * generated by the Apache POI library.
 *
 */
@CrossOrigin(origins = "*", maxAge = 3600)
@RestController
@RequestMapping("/api")
public class AttendanceAPI {
	private AttendanceService attendanceService;
    /**
     * Handle request to download an Excel document
     */
	@Autowired
    public AttendanceAPI(AttendanceService attendanceService, ExcelAttendanceReport report) {
        this.attendanceService = attendanceService;
    }
    @RequestMapping(value = "/attendanceExcel", method = RequestMethod.GET)
    public ModelAndView attendanceExcel() {
        // take some data
        List<Attendance> listAttendance = new ArrayList<Attendance>();
        listAttendance = attendanceService.listAttendance();
        // return a view which will be resolved by an excel view resolver
        return new ModelAndView("attendanceView", "listAttendance", listAttendance);
   }
}